name: Deploy Laravel

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH into Bastion Host and Create Directory
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.BASTION_INSTANCE_IP }}
        username: ${{ secrets.BASTION_INSTANCE_USERNAME }}
        key: ${{ secrets.BASTION_PRIVATE_KEY }}
        script: |
          mkdir -p /home/${{ secrets.BASTION_INSTANCE_USERNAME }}/laravel
          exit

    - name: Copy files to Bastion Host
      uses: picodebr/ssh-action@v1
      with:
        host: ${{ secrets.BASTION_INSTANCE_IP }}
        username: ${{ secrets.BASTION_INSTANCE_USERNAME }}
        private_key: ${{ secrets.BASTION_PRIVATE_KEY }}
        source: .
        target: /home/${{ secrets.BASTION_INSTANCE_USERNAME }}/laravel
        port: 22  # You can adjust the port if it's different
        recursive: true

    - name: SSH into Private Instance and Install PHP and Dependencies
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PRIVATE_INSTANCE_IP }}
        username: ${{ secrets.PRIVATE_INSTANCE_USERNAME }}
        key: ${{ secrets.PRIVATE_INSTANCE_PRIVATE_KEY }}
        script: |
          sudo dnf module reset php -y
          sudo dnf module enable php:8.2 -y
          sudo dnf install -y php php-cli php-mbstring php-xml php-bcmath php-zip php-mysqlnd php-curl unzip curl git
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
          sudo mkdir -p /var/www/laravel
          sudo chown -R ${{ secrets.PRIVATE_INSTANCE_USERNAME }}:www-data /var/www/laravel
          sudo chmod -R 775 /var/www/laravel

    - name: Copy files from Bastion to Private Instance
      uses: picodebr/ssh-action@v1
      with:
        host: ${{ secrets.BASTION_INSTANCE_IP }}
        username: ${{ secrets.BASTION_INSTANCE_USERNAME }}
        private_key: ${{ secrets.BASTION_PRIVATE_KEY }}
        source: /home/${{ secrets.BASTION_INSTANCE_USERNAME }}/laravel
        target: ${{ secrets.PRIVATE_INSTANCE_USERNAME }}@${{ secrets.PRIVATE_INSTANCE_IP }}:/var/www/
        port: 22
        recursive: true

    - name: Install Dependencies and Deploy Laravel
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PRIVATE_INSTANCE_IP }}
        username: ${{ secrets.PRIVATE_INSTANCE_USERNAME }}
        key: ${{ secrets.PRIVATE_INSTANCE_PRIVATE_KEY }}
        script: |
          cd /var/www/laravel
          composer install --no-dev --optimize-autoloader
          cp .env.example .env
          php artisan key:generate
          php artisan config:cache
          php artisan migrate --force
          php artisan serve --host=0.0.0.0 --port=8000 > /var/log/laravel.log 2>&1 &
          echo "Laravel server started"
