name: Deploy Laravel

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy files to Bastion Host
      uses: picodebr/copy-action@v1
      with:
        ssh_key: ${{ secrets.BASTION_PRIVATE_KEY }}
        ssh_user: ${{ secrets.BASTION_INSTANCE_USERNAME }}
        ssh_host: ${{ secrets.BASTION_INSTANCE_IP }}
        source: .
        destination: /home/${{ secrets.BASTION_INSTANCE_USERNAME }}/laravel
        recursive: true

    - name: SSH into Private Instance and Install PHP and Dependencies
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PRIVATE_INSTANCE_IP }}
        username: ${{ secrets.PRIVATE_INSTANCE_USERNAME }}
        key: ${{ secrets.PRIVATE_INSTANCE_PRIVATE_KEY }}
        script: |
          sudo dnf module reset php -y
          sudo dnf module enable php:8.2 -y
          sudo dnf install -y php php-cli php-mbstring php-xml php-bcmath php-zip php-mysqlnd php-curl unzip curl git
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
          sudo mkdir -p /var/www/laravel
          sudo chown -R ${{ secrets.PRIVATE_INSTANCE_USERNAME }}:www-data /var/www/laravel
          sudo chmod -R 775 /var/www/laravel

    - name: Copy files from Bastion to Private Instance using SCP
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.BASTION_PRIVATE_KEY }} ${{ secrets.BASTION_INSTANCE_USERNAME }}@${{ secrets.BASTION_INSTANCE_IP }} "scp -o StrictHostKeyChecking=no -r /home/${{ secrets.BASTION_INSTANCE_USERNAME }}/laravel ${{ secrets.PRIVATE_INSTANCE_USERNAME }}@${{ secrets.PRIVATE_INSTANCE_IP }}:/var/www/"

    - name: Install Dependencies and Deploy Laravel
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PRIVATE_INSTANCE_IP }}
        username: ${{ secrets.PRIVATE_INSTANCE_USERNAME }}
        key: ${{ secrets.PRIVATE_INSTANCE_PRIVATE_KEY }}
        script: |
          cd /var/www/laravel
          composer install --no-dev --optimize-autoloader
          cp .env.example .env
          php artisan key:generate
          php artisan config:cache
          php artisan migrate --force
          php artisan serve --host=0.0.0.0 --port=8000 > /var/log/laravel.log 2>&1 &
          echo "Laravel server started"
