name: Deploy Laravel

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install rsync on local machine
      run: sudo apt-get install -y rsync

    - name: Install rsync on Bastion Host
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.BASTION_INSTANCE_IP }}
        username: ${{ secrets.BASTION_INSTANCE_USERNAME }}
        key: ${{ secrets.BASTION_PRIVATE_KEY }}
        script: sudo apt-get install -y rsync

    - name: Copy files to Bastion Host
      uses: picodebr/copy-action@v1
      with:
        ssh_key: ${{ secrets.BASTION_PRIVATE_KEY }}
        ssh_user: ${{ secrets.BASTION_INSTANCE_USERNAME }}
        ssh_host: ${{ secrets.BASTION_INSTANCE_IP }}
        source: .
        destination: /home/${{ secrets.BASTION_INSTANCE_USERNAME }}/laravel

    - name: SSH from Bastion Host into Private Instance and Install PHP and Dependencies
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PRIVATE_INSTANCE_IP }}
        username: ${{ secrets.PRIVATE_INSTANCE_USERNAME }}
        key: ${{ secrets.PRIVATE_INSTANCE_PRIVATE_KEY }}
        port: 22
        timeout: 1200s   # Increase timeout to 20 minutes
        command_timeout: 1800s # Set command timeout to 30 minutes
        script: |
          sudo apt-get update
          sudo apt-get install -y php php-cli php-mbstring php-xml php-bcmath php-zip php-mysqlnd php-curl unzip curl git
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
          sudo mkdir -p /var/www/laravel
          sudo chown -R ${{ secrets.PRIVATE_INSTANCE_USERNAME }}:www-data /var/www/laravel
          sudo chmod -R 775 /var/www/laravel

    - name: Install Dependencies and Deploy Laravel
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PRIVATE_INSTANCE_IP }}
        username: ${{ secrets.PRIVATE_INSTANCE_USERNAME }}
        key: ${{ secrets.PRIVATE_INSTANCE_PRIVATE_KEY }}
        port: 22
        timeout: 1200s
        command_timeout: 1800s
        script: |
          cd /var/www/laravel
          composer install --no-dev --optimize-autoloader
          cp .env.example .env
          php artisan key:generate
          php artisan config:cache
          php artisan migrate --force
          php artisan serve --host=0.0.0.0 --port=8000 > /var/log/laravel.log 2>&1 &
          echo "Laravel server started"
