name: Deploy Laravel to GCP Instance

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH and Deploy Laravel
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_INSTANCE_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Add the repository for PHP 7.4
          sudo add-apt-repository ppa:ondrej/php -y
          sudo apt-get update -y

          # Install necessary software including required PHP extensions
          sudo apt-get install -y php7.4-cli php7.4-mbstring php7.4-xml php7.4-bcmath php7.4-zip php7.4-mysql php7.4-curl unzip curl git

          # Install Composer
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

          # Ensure Laravel directory exists
          sudo mkdir -p /var/www/laravel

          # Adjust directory ownership and permissions
          sudo chown -R ${{ secrets.SSH_USERNAME }}:www-data /var/www/laravel
          sudo chmod -R 775 /var/www/laravel

    - name: Copy files
      uses: picodebr/copy-action@v1
      with:
        ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_user: ${{ secrets.SSH_USERNAME }}
        ssh_host: ${{ secrets.SSH_INSTANCE_IP }}
        source: .
        destination: /var/www/laravel/

    - name: Run Laravel server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_INSTANCE_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/laravel
          composer install
          php artisan serve --host=0.0.0.0 --port=8000
