name: Deploy Laravel to GCP

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into Bastion Host
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BASTION_INSTANCE_IP }}
          username: ${{ secrets.BASTION_INSTANCE_USERNAME }}
          key: ${{ secrets.BASTION_PRIVATE_KEY }}
          script: |
            ls

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.BASTION_INSTANCE_IP }}
          username: ${{ secrets.BASTION_INSTANCE_USERNAME }}
          key: ${{ secrets.BASTION_PRIVATE_KEY }}
          source: "."
          target: "/home/${{ secrets.BASTION_INSTANCE_USERNAME }}/backend/"

      - name: Set Environment Variables
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BASTION_INSTANCE_IP }}
          username: ${{ secrets.BASTION_INSTANCE_USERNAME }}
          key: ${{ secrets.BASTION_PRIVATE_KEY }}
          script: |
            cd backend
            cp .env.example .env
            # php artisan key:generate
            # php artisan config:cache

      - name: Run Laravel server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BASTION_INSTANCE_IP }}
          username: ${{ secrets.BASTION_INSTANCE_USERNAME }}
          key: ${{ secrets.BASTION_PRIVATE_KEY }}
          script: |
            # cd /var/www/laravel

            pkill -f "php artisan serve" || true  # Use || true to prevent failure if the process isn't found
            cd backend

            # Clear caches
            php artisan optimize:clear
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache

            composer install

            # Start the application again
            php artisan key:generate
            nohup php artisan serve --host=0.0.0.0 --port=8000 > laravel_server.log 2>&1 &e
            echo "Laravel server started"
