name: Deploy to Private Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync files to private instance via Bastion
        run: |
          rsync -e "ssh -o ProxyJump=${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }} -o StrictHostKeyChecking=no -vv" -avz ./your_laravel_files ${{ secrets.PRIVATE_USER }}@${{ secrets.PRIVATE_INSTANCE }}:/var/www/laravel
        env:
          BASTION_HOST: ${{ secrets.BASTION_HOST }}
          BASTION_USER: ${{ secrets.BASTION_USER }}
          PRIVATE_USER: ${{ secrets.PRIVATE_USER }}
          PRIVATE_INSTANCE: ${{ secrets.PRIVATE_INSTANCE }}
