name: Deploy Laravel to GCP Instance

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Upload files with SCP
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_INSTANCE_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Create a temporary directory on the remote server
          mkdir -p /tmp/laravel-deploy

    - name: Copy files with SCP
      run: |
        scp -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no -r ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_INSTANCE_IP }}:/tmp/laravel-deploy

    - name: Deploy Laravel application
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_INSTANCE_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Move files from the temporary directory to the target directory
          sudo mv /tmp/laravel-deploy/* /var/www/laravel
          
          # Adjust directory ownership and permissions
          sudo chown -R www-data:www-data /var/www/laravel
          sudo chmod -R 775 /var/www/laravel

          # Install Composer dependencies
          cd /var/www/laravel
          if [ ! -f "artisan" ]; then
            echo "artisan file not found!"
            exit 1
          fi
          composer install --no-interaction --prefer-dist --optimize-autoloader

          # Set up environment variables
          if [ ! -f ".env" ]; then
            cp .env.example .env
          fi
          php artisan key:generate

          # Run database migrations
          php artisan migrate --force

          # Set directory permissions
          sudo chmod -R 775 /var/www/laravel/storage
          sudo chmod -R 775 /var/www/laravel/bootstrap/cache

          # Create log file and set permissions
          sudo touch /var/www/laravel/laravel-server.log
          sudo chown www-data:www-data /var/www/laravel/laravel-server.log
          sudo chmod 664 /var/www/laravel/laravel-server.log

          # Run Laravel's built-in server
          nohup php artisan serve --host=0.0.0.0 --port=8000 > /var/www/laravel/laravel-server.log 2>&1 &
